"""Constants go here"""
POLKADOT_TREASURY = "13UVJyLnbVp9RBZYFwFGyDvVd1y27Tt8tkntv6Q7JVPhFsTB"
DECIMAL_AFTER_REDENOMINATION = 1.0 * (10 ** 10)
SIDECAR_RETRIES = 5
SIDECAR_RETRY_DELAY_IN_SECONDS = 10
NEAREST_BLOCK_THRESHOLD_IN_SECONDS = 5
REWARD_DESTINATION_STASH = "Stash"
REWARD_DESTINATION_STAKED = "Staked"
REWARD_DESTINATION_CONTROLLER = "Stash"
REWARD_DESTINATION_ACCOUNT = "Account"
