"""Constants go here"""
POLKADOT_TREASURY = "13UVJyLnbVp9RBZYFwFGyDvVd1y27Tt8tkntv6Q7JVPhFsTB"
DECIMAL_AFTER_REDENOMINATION = 1.0 * (10 ** 10)
SIDECAR_RETRIES = 5
SIDECAR_RETRY_DELAY_IN_SECONDS = 10
POLKADOT_BLOCK_CREATION_TIME_SECONDS = 6
